@NegoSudAPI_HostAddress = https://localhost:7211

GET {{NegoSudAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{NegoSudAPI_HostAddress}}/api/produits/Categorie/1
Accept: application/json
###

GET {{NegoSudAPI_HostAddress}}/api/produits/
Accept: application/json
###

GET {{NegoSudAPI_HostAddress}}/api/Categories/1
Accept: application/json
###
GET {{NegoSudAPI_HostAddress}}/api/Commandes/statut/3
Accept: application/json
###
GET {{NegoSudAPI_HostAddress}}/api/Commandes/
Accept: application/json
###

POST {{NegoSudAPI_HostAddress}}/api/employes
Content-Type: application/json

{
  "userName": "JulietteDu31",
  "nomUtilisateur": "Legendre",
  "prenomUtilisateur": "Juliette",
  "adresseUtilisateur": "rue du test",
  "mailUtilisateur": "juliette@mail.fr",
  "numTelUtilisateur": "0123456789",
  "motDePasse": "mdpMDP&1",
  "gerant": true
}

###
 

POST {{NegoSudAPI_HostAddress}}/api/produits
Content-Type: application/json

{
  "NomProduit":"vino testo",
  "contenanceCl": 750,
  "qteEnStock": 100,
  "degreeAlcool": 13.5,
  "millesime": 2020,
  "qteCarton": 12,
  "photoProduitPath": "D:/",
  "descriptionProduit": "A vin à tester.",
  "seuilCommandeMin": 20,
  "commandeMin": 5,
  "idDomaine": 1,
  "idCategorie": 1,
  "alaVente": true,
  "prixAchat": {
    "dateDebut": "2024-01-22T09:47:58.224Z",
    "prixCarton": 120,
    "prixUnite": 10,
    "fournisseurId": 1
  },
  "prixVente": {
    "dateDebut": "2024-01-22T09:47:58.224Z",
    "prixCarton": 150,
    "prixUnite": 15,
    "promotion": 0.1,
    "taxe": 0.05
  }
}

###

POST {{NegoSudAPI_HostAddress}}/api/commandes
Content-Type: application/json

{
  "qteMouvement": 0,
  "dateMouvement": "2024-01-25T10:17:01.912Z",
  "entreeOuSortie": true,
  "commentaire": "Ceci est un commande test",
  "employeId": 1,
  "detailMouvementStocks": [
    {
      "qteProduit": 6,
      "prixApresRistourne": -1,
      "auCarton": false,
      "produitId": 1
    },
    {
      "qteProduit": 2,
      "prixApresRistourne": 12,
      "auCarton": false,
      "produitId": 2
    }
  ],
  "statutCommande": 0,
  "fournisseurId": 1
}

###

  

GET {{NegoSudAPI_HostAddress}}/api/commandes/COM001

###

GET {{NegoSudAPI_HostAddress}}/api/ventes/

###


POST {{NegoSudAPI_HostAddress}}/api/ventes/
Content-Type: application/json

{
  "qteMouvement": 1,
  "commentaire": "Ceci est une vente TEST",
  "employeId": 1,
  "detailMouvementStocks": [
    {
      "qteProduit": 1,
      "prixApresRistourne": 12,
      "auCarton": false,
      "mouvementStockId": 0,
      "produitId": 5
    },
    {
        "qteProduit": 2,
        "prixApresRistourne": -1,
        "auCarton": false,
        "mouvementStockId": 0,
        "produitId": 6
     }
  ],
  "clientId": 7
}

###
POST {{NegoSudAPI_HostAddress}}/api/autreMouvement
Content-Type: application/json

{
  "commentaire": "Ceci est un autre mouvement TEST",
  "employeId": 1,
  "detailMouvementStocks": [
    {
      "qteProduit": -1,
      "prixApresRistourne": -1,
      "auCarton": false,
      "mouvementStockId": 0,
      "produitId": 1
    },
    {
        "qteProduit": 2,
        "prixApresRistourne": -1,
        "auCarton": false,
        "mouvementStockId": 0,
        "produitId": 2
     }
  ],
  "typeMouvementId": 1
}

###


POST {{NegoSudAPI_HostAddress}}/api/employes
Content-Type: application/json

{
  "userName": "JulietteDu31",
  "nomUtilisateur": "Legendre",
  "prenomUtilisateur": "Juliette",
  "adresseUtilisateur": "rue du test",
  "mailUtilisateur": "juliette@mail.fr",
  "numTelUtilisateur": "0123456789",
  "motDePasse": "mdpMDP&1",
  "gerant": true
}

###
POST {{NegoSudAPI_HostAddress}}/api/Client
Content-Type: application/json

{
  "userName": "Jose666",
  "nomUtilisateur": "NATAS",
  "prenomUtilisateur": "José",
  "adresseUtilisateur": "rue du test",
  "mailUtilisateur": "Jose@mail.fr",
  "numTelUtilisateur": "0123456789",
  "motDePasse": "mdpMDP&1"
}

###


POST {{NegoSudAPI_HostAddress}}/login?useCookies=true&useSessionCookies=true
Content-Type: application/json

{
  "email": "JulietteDu31",
  "password": "mdpMDP&1",
  "twoFactorCode": "string",
  "twoFactorRecoveryCode": "string"
}

###

DELETE {{NegoSudAPI_HostAddress}}/api/client/6

###

PUT {{NegoSudAPI_HostAddress}}/api/produits/1
Content-Type: application/json

{
  //ProduitWriteDTO
}

###

PUT {{NegoSudAPI_HostAddress}}/api/produits/0
Content-Type: application/json

{
  //ProduitWriteDTO
}

###

PUT {{NegoSudAPI_HostAddress}}/api/produits/1
Content-Type: application/json

{
  "id": 1,
  "nomProduit": "string",
  "contenanceCl": 0,
  "qteEnStock": 0,
  "degreeAlcool": 0,
  "millesime": 0,
  "qteCarton": 0,
  "photoProduitPath": "string",
  "descriptionProduit": "string",
  "seuilCommandeMin": 0,
  "commandeMin": 0,
  "idDomaine":1 ,
  "idCategorie": 1,
  "alaVente": true,
   "prixAchat": {
    "dateDebut": "2024-02-13T17:02:30.502Z",
    "prixCarton": 6,
    "prixUnite": 6,
    "produitId": 1,
    "fournisseurId": 1
  },
  "prixVente": {
    "dateDebut": "2024-02-13T17:02:30.502Z",
    "prixCarton": 1,
    "prixUnite": 1,
    "produitId": 1,
    "promotion": 0,
    "taxe": 0
  }
}

###
